/**
 * Construction preset — building/construction themed content.
 */

import type { SeedPreset } from './types'

export const constructionPreset: SeedPreset = {
  name: 'construction',
  label: 'Construction / Building',
  description: 'Complete construction and building firm example content.',

  siteSettings: {
    siteName: 'Apex Builders Co.',
    tagline: 'Building Tomorrow, Today.',
    phone: '+1 (555) 987-6543',
    email: 'info@apexbuilders.com',
    address: '789 Industrial Park Road, Building District, Metro City 20001',
    socialMedia: [
      { platform: 'Facebook', url: 'https://facebook.com/apexbuilders' },
      { platform: 'Instagram', url: 'https://instagram.com/apexbuilders' },
      { platform: 'LinkedIn', url: 'https://linkedin.com/company/apexbuilders' },
    ],
  },

  services: [
    {
      title: 'Commercial Construction',
      slug: 'commercial-construction',
      shortDescription: 'Full-service commercial building construction from ground-up to completion.',
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Commercial Construction', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'We deliver large-scale commercial construction projects including office buildings, retail complexes, and mixed-use developments. Our project management team ensures on-time, on-budget delivery with uncompromising quality standards.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'Services include site planning, foundation work, structural steel, MEP installation, interior fit-out, and final commissioning.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
      order: 1,
    },
    {
      title: 'Residential Development',
      slug: 'residential-development',
      shortDescription: 'Custom home building and residential community development projects.',
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Residential Development', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'From custom luxury homes to large-scale residential communities, we bring your vision to life. Our team handles every aspect of residential construction including architectural coordination, permitting, and quality assurance.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
      order: 2,
    },
    {
      title: 'Renovation & Retrofitting',
      slug: 'renovation-retrofitting',
      shortDescription: 'Building renovation, structural retrofitting, and adaptive reuse projects.',
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Renovation & Retrofitting', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'We specialize in transforming existing structures through renovation and adaptive reuse. Whether it is seismic retrofitting, energy efficiency upgrades, or complete interior remodeling, our team delivers results that meet modern standards.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
      order: 3,
    },
    {
      title: 'Infrastructure Projects',
      slug: 'infrastructure-projects',
      shortDescription: 'Roads, bridges, utilities, and civil infrastructure construction.',
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Infrastructure Construction', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'Our infrastructure division handles roads, bridges, drainage systems, and utility installations. We work with government agencies and private developers to deliver critical infrastructure projects on schedule.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
      order: 4,
    },
    {
      title: 'Project Management & Consulting',
      slug: 'project-management-consulting',
      shortDescription: 'Expert construction management, cost estimation, and feasibility consulting.',
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Project Management', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'Our experienced project managers oversee every phase of construction from pre-construction planning through project closeout. We provide cost estimation, scheduling, risk management, and quality control services.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
      order: 5,
    },
  ],

  categories: [
    { name: 'Industry Insights', slug: 'industry-insights' },
    { name: 'Project Updates', slug: 'project-updates' },
  ],

  posts: [
    {
      title: 'Sustainable Building Practices in 2024',
      slug: 'sustainable-building-practices-2024',
      type: 'artikel' as const,
      excerpt: 'How green building standards are reshaping the construction industry.',
      status: 'published' as const,
      publishedAt: new Date('2024-01-15').toISOString(),
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Sustainable Construction', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'The construction industry is increasingly adopting sustainable building practices. From LEED certification to net-zero energy buildings, green construction is no longer optional but expected by clients and regulators alike.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
    {
      title: 'The Future of Modular Construction',
      slug: 'future-modular-construction',
      type: 'artikel' as const,
      excerpt: 'How prefabricated and modular building techniques are reducing costs and timelines.',
      status: 'published' as const,
      publishedAt: new Date('2024-02-20').toISOString(),
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Modular Construction', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'Modular construction is gaining traction as a solution to labor shortages and rising material costs. By fabricating building components off-site and assembling them on-site, projects can be completed faster with less waste.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
    {
      title: 'New Downtown Office Tower Completed',
      slug: 'downtown-office-tower-completed',
      type: 'blog' as const,
      excerpt: 'We are proud to announce the completion of our 25-story commercial tower in the city center.',
      status: 'published' as const,
      publishedAt: new Date('2024-03-10').toISOString(),
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Tower Completion', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'After 18 months of construction, our flagship 25-story commercial office tower is now complete and ready for occupancy. The project features a modern glass facade, green building certification, and state-of-the-art building management systems.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
    {
      title: 'Safety First: Our Zero-Incident Record',
      slug: 'safety-zero-incident-record',
      type: 'blog' as const,
      excerpt: 'Celebrating 500,000 hours without a lost-time incident across all our active sites.',
      status: 'published' as const,
      publishedAt: new Date('2024-04-05').toISOString(),
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Safety Record', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'We are proud to celebrate 500,000 hours without a lost-time incident across all our active construction sites. Our commitment to safety training, proper equipment, and strict protocols continues to deliver results.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
  ],

  pages: [
    {
      title: 'About Us',
      slug: 'about-us',
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'About Apex Builders Co.', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h1',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'Apex Builders Co. is a premier construction firm with over 25 years of experience delivering commercial, residential, and infrastructure projects. Our commitment to quality, safety, and on-time delivery has earned us a reputation as a trusted partner in the industry.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Our Vision', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'To be the most trusted construction firm in the region, known for building structures that stand the test of time and communities that thrive.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Our Values', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'Safety First — Quality Always — Integrity in Every Project — Innovation in Every Solution — Community Responsibility',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
  ],

  landing: {
    heroTitle: 'Building Excellence, One Project at a Time',
    heroSubtitle: 'Apex Builders delivers world-class construction solutions for commercial, residential, and infrastructure projects.',
    heroCtaLabel: 'View Our Projects',
    heroCtaLink: '/services',
    stats: [
      { label: 'Projects Completed', value: '200+' },
      { label: 'Square Meters Built', value: '1.5M+' },
      { label: 'Team Members', value: '350+' },
      { label: 'Years of Experience', value: '25+' },
    ],
  },
}
