/**
 * Generic preset — neutral placeholder content for any business type.
 */

import type { SeedPreset } from './types'

export const genericPreset: SeedPreset = {
  name: 'generic',
  label: 'Generic (Placeholder Business)',
  description: 'Neutral placeholder content suitable for any business type.',

  siteSettings: {
    siteName: 'Your Company',
    tagline: 'Building the future, one solution at a time.',
    phone: '+1 (555) 000-0000',
    email: 'hello@yourcompany.com',
    address: '123 Business Street, Suite 100, City, State 00000',
    socialMedia: [
      { platform: 'LinkedIn', url: 'https://linkedin.com/company/yourcompany' },
      { platform: 'Instagram', url: 'https://instagram.com/yourcompany' },
      { platform: 'Twitter', url: 'https://twitter.com/yourcompany' },
    ],
  },

  services: [
    {
      title: 'Consulting',
      slug: 'consulting',
      shortDescription: 'Expert advisory services to help your business grow and optimize operations.',
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Consulting Services', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'Our consulting team brings years of industry experience to help your organization navigate complex challenges and seize growth opportunities.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'We offer strategic planning, operational optimization, and change management services tailored to your unique business needs.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
      order: 1,
    },
    {
      title: 'Technology Solutions',
      slug: 'technology-solutions',
      shortDescription: 'Modern technology solutions to streamline your workflows and boost productivity.',
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Technology Solutions', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'From software development to cloud infrastructure, we deliver technology solutions that drive efficiency and innovation across your organization.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'Our team specializes in custom software development, system integration, cloud migration, and IT infrastructure management.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
      order: 2,
    },
    {
      title: 'Training & Development',
      slug: 'training-development',
      shortDescription: 'Professional training programs to upskill your workforce and enhance team performance.',
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Training & Development', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'Invest in your people with our comprehensive training and development programs designed to build skills, boost confidence, and improve performance.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
      order: 3,
    },
  ],

  categories: [
    { name: 'Industry News', slug: 'industry-news' },
    { name: 'Company Updates', slug: 'company-updates' },
  ],

  posts: [
    {
      title: 'How Technology Is Transforming Modern Business',
      slug: 'technology-transforming-business',
      type: 'artikel' as const,
      excerpt: 'An overview of how modern technology solutions are reshaping business operations worldwide.',
      status: 'published' as const,
      publishedAt: new Date('2024-01-15').toISOString(),
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Technology in Business', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'Technology continues to be a driving force behind business transformation. From automation to artificial intelligence, companies are leveraging new tools to improve efficiency and customer experience.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'Organizations that embrace digital transformation are seeing measurable improvements in productivity, cost reduction, and competitive advantage.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
    {
      title: '5 Strategies for Effective Business Growth',
      slug: 'strategies-business-growth',
      type: 'artikel' as const,
      excerpt: 'Key strategies that can help your business scale sustainably in a competitive market.',
      status: 'published' as const,
      publishedAt: new Date('2024-02-20').toISOString(),
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Growth Strategies', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'Sustainable business growth requires a combination of strategic planning, operational efficiency, and customer-centric approaches. Here are five proven strategies that can help your business scale.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
    {
      title: 'Company Expansion: New Office Opening',
      slug: 'new-office-opening',
      type: 'blog' as const,
      excerpt: 'We are excited to announce the opening of our new regional office.',
      status: 'published' as const,
      publishedAt: new Date('2024-03-10').toISOString(),
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'New Office', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'We are proud to announce the opening of our new regional office. This expansion reflects our commitment to serving our clients better and expanding our reach into new markets.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
    {
      title: 'Building a Strong Team Culture',
      slug: 'strong-team-culture',
      type: 'blog' as const,
      excerpt: 'Tips on fostering a positive and productive workplace culture.',
      status: 'published' as const,
      publishedAt: new Date('2024-04-05').toISOString(),
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Team Culture', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'A strong team culture is the foundation of any successful organization. It drives engagement, retention, and overall performance.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
  ],

  pages: [
    {
      title: 'About Us',
      slug: 'about-us',
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'About Our Company', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h1',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'We are a forward-thinking company dedicated to delivering exceptional value to our clients. With a team of experienced professionals, we provide comprehensive solutions that help businesses achieve their goals.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Our Vision', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'To be the leading provider of innovative solutions that empower businesses to reach their full potential.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Our Mission', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: '1. Deliver high-quality solutions that exceed client expectations\n2. Foster innovation and continuous improvement\n3. Build lasting partnerships based on trust and reliability\n4. Empower our team to make a positive impact',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
  ],

  landing: {
    heroTitle: 'Empowering Your Business with Innovative Solutions',
    heroSubtitle: 'We provide comprehensive solutions to help your business thrive in a competitive landscape.',
    heroCtaLabel: 'Explore Our Services',
    heroCtaLink: '/services',
    stats: [
      { label: 'Projects Completed', value: '500+' },
      { label: 'Happy Clients', value: '200+' },
      { label: 'Team Members', value: '50+' },
      { label: 'Years of Experience', value: '10+' },
    ],
  },
}
