/**
 * Hospital preset — medical/healthcare themed content.
 */

import type { SeedPreset } from './types'

export const hospitalPreset: SeedPreset = {
  name: 'hospital',
  label: 'Hospital / Healthcare',
  description: 'Complete hospital and healthcare facility example content.',

  siteSettings: {
    siteName: 'St. Mary Medical Center',
    tagline: 'Compassionate Care, Advanced Medicine.',
    phone: '+1 (555) 123-4567',
    email: 'info@stmarymedical.com',
    address: '456 Health Avenue, Medical District, Metro City 10001',
    socialMedia: [
      { platform: 'Facebook', url: 'https://facebook.com/stmarymedical' },
      { platform: 'Instagram', url: 'https://instagram.com/stmarymedical' },
      { platform: 'LinkedIn', url: 'https://linkedin.com/company/stmarymedical' },
    ],
  },

  services: [
    {
      title: 'Emergency Services',
      slug: 'emergency-services',
      shortDescription: '24/7 emergency medical care with state-of-the-art trauma and critical care facilities.',
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Emergency Department', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'Our emergency department operates 24 hours a day, 7 days a week, providing immediate medical attention for urgent and life-threatening conditions. Equipped with advanced diagnostic tools and staffed by experienced emergency physicians and nurses.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'Services include trauma care, cardiac emergency, pediatric emergency, stroke treatment, and ambulance dispatch coordination.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
      order: 1,
    },
    {
      title: 'Surgery & Operating Theater',
      slug: 'surgery-operating-theater',
      shortDescription: 'Advanced surgical suites with minimally invasive and robotic-assisted procedures.',
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Surgical Services', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'Our operating theater features the latest in minimally invasive and robotic-assisted surgical technology. Our team of board-certified surgeons performs a wide range of procedures across multiple specialties.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
      order: 2,
    },
    {
      title: 'Maternity & Neonatal Care',
      slug: 'maternity-neonatal-care',
      shortDescription: 'Comprehensive maternity services with Level III NICU for high-risk pregnancies.',
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Maternity & Neonatal Care', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'Our maternity center provides comprehensive prenatal, delivery, and postpartum care. The Level III NICU is equipped to handle premature and high-risk newborn cases with 24/7 neonatal specialist coverage.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
      order: 3,
    },
    {
      title: 'Diagnostic Imaging',
      slug: 'diagnostic-imaging',
      shortDescription: 'Full-service imaging center with MRI, CT scan, ultrasound, and digital X-ray.',
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Diagnostic Imaging Center', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'Our diagnostic imaging center offers a full range of imaging services including MRI, CT scan, ultrasound, digital X-ray, mammography, and nuclear medicine. Results are typically available within hours.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
      order: 4,
    },
    {
      title: 'Outpatient & Specialist Clinics',
      slug: 'outpatient-specialist-clinics',
      shortDescription: 'Over 30 specialist clinics covering cardiology, orthopedics, neurology, and more.',
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Outpatient Clinics', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'We operate over 30 specialist outpatient clinics covering cardiology, orthopedics, neurology, dermatology, endocrinology, gastroenterology, and many more. Appointments can be made online or by phone.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
      order: 5,
    },
  ],

  categories: [
    { name: 'Health Tips', slug: 'health-tips' },
    { name: 'Medical News', slug: 'medical-news' },
    { name: 'Hospital Updates', slug: 'hospital-updates' },
  ],

  posts: [
    {
      title: 'Understanding Heart Health: A Comprehensive Guide',
      slug: 'understanding-heart-health',
      type: 'artikel' as const,
      excerpt: 'Learn about cardiovascular health, risk factors, and prevention strategies for heart disease.',
      status: 'published' as const,
      publishedAt: new Date('2024-01-15').toISOString(),
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Heart Health', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'Heart disease remains the leading cause of death worldwide. Understanding the risk factors and adopting a heart-healthy lifestyle can significantly reduce your chances of developing cardiovascular disease.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'Key risk factors include high blood pressure, high cholesterol, obesity, smoking, and physical inactivity. Regular check-ups and screening can help detect problems early.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
    {
      title: 'When to Visit the Emergency Room',
      slug: 'when-visit-emergency-room',
      type: 'artikel' as const,
      excerpt: 'A guide to recognizing symptoms that require immediate medical attention.',
      status: 'published' as const,
      publishedAt: new Date('2024-02-20').toISOString(),
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Emergency Room Guidelines', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'Knowing when to seek emergency medical care can save your life. Here are the key symptoms and situations that warrant an immediate visit to the emergency room.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
    {
      title: 'New Pediatric Wing Now Open',
      slug: 'new-pediatric-wing-open',
      type: 'blog' as const,
      excerpt: 'Our state-of-the-art pediatric wing is now open, offering enhanced care for young patients.',
      status: 'published' as const,
      publishedAt: new Date('2024-03-10').toISOString(),
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Pediatric Wing', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'We are thrilled to announce the opening of our new pediatric wing. Designed with children in mind, the facility features colorful environments, play areas, and specialized equipment for young patients from newborn to adolescence.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
    {
      title: 'Telemedicine Services Expanded',
      slug: 'telemedicine-expanded',
      type: 'blog' as const,
      excerpt: 'Virtual consultations now available across all specialties.',
      status: 'published' as const,
      publishedAt: new Date('2024-04-05').toISOString(),
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Telemedicine Expansion', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'Our telemedicine platform has been expanded to cover all medical specialties. Patients can now consult with specialists from the comfort of their homes via secure video calls.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
  ],

  pages: [
    {
      title: 'About Us',
      slug: 'about-us',
      content: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'About St. Mary Medical Center', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h1',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'St. Mary Medical Center has been serving the community since 1985. As a leading healthcare provider, we combine advanced medical technology with compassionate care to deliver the best possible outcomes for our patients.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Our Mission', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'To provide accessible, high-quality healthcare services that improve the health and well-being of our community through compassionate care, medical excellence, and innovation.',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
            {
              type: 'heading',
              version: 1,
              children: [{ type: 'text', text: 'Our Values', detail: 0, format: 1, mode: 'normal', style: '' }],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
            },
            {
              type: 'paragraph',
              version: 1,
              children: [
                {
                  type: 'text',
                  version: 1,
                  text: 'Compassion — Integrity — Excellence — Innovation — Patient-Centered Care',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
  ],

  landing: {
    heroTitle: 'Your Health Is Our Priority',
    heroSubtitle: 'St. Mary Medical Center provides world-class healthcare with compassionate, patient-centered services.',
    heroCtaLabel: 'Find a Doctor',
    heroCtaLink: '/services',
    stats: [
      { label: 'Beds Available', value: '450+' },
      { label: 'Specialists', value: '120+' },
      { label: 'Patients Served Yearly', value: '50,000+' },
      { label: 'Years of Service', value: '40+' },
    ],
  },
}
